#ifndef END_CREDITS_LOGO_H
#define END_CREDITS_LOGO_H

#include <stdint.h>

#define END_CREDITS_LOGO_W 128
#define END_CREDITS_LOGO_H 84
#define END_CREDITS_LOGO_PAL_SIZE 16

extern const uint16_t END_CREDITS_LOGO_PAL[END_CREDITS_LOGO_PAL_SIZE];
extern const uint8_t  END_CREDITS_LOGO_IDX[(END_CREDITS_LOGO_W * END_CREDITS_LOGO_H) / 2];

#endif // END_CREDITS_LOGO_H
