#ifndef GAME_STORY_LOGO_H
#define GAME_STORY_LOGO_H

#include <stdint.h>

#define GAME_STORY_LOGO_W 128
#define GAME_STORY_LOGO_H 72
#define GAME_STORY_LOGO_PAL_SIZE 16

extern const uint16_t GAME_STORY_LOGO_PAL[GAME_STORY_LOGO_PAL_SIZE];
extern const uint8_t  GAME_STORY_LOGO_IDX[(GAME_STORY_LOGO_W * GAME_STORY_LOGO_H) / 2];

#endif // GAME_STORY_LOGO_H
