#ifndef GAME_OPENING_SCREEN_LOGO_H
#define GAME_OPENING_SCREEN_LOGO_H

#include <stdint.h>

#define GAME_OPENING_SCREEN_LOGO_W 128
#define GAME_OPENING_SCREEN_LOGO_H 128
#define GAME_OPENING_SCREEN_LOGO_PAL_SIZE 16

extern const uint16_t GAME_OPENING_SCREEN_LOGO_PAL[GAME_OPENING_SCREEN_LOGO_PAL_SIZE];
extern const uint8_t  GAME_OPENING_SCREEN_LOGO_IDX[(GAME_OPENING_SCREEN_LOGO_W * GAME_OPENING_SCREEN_LOGO_H) / 2];

#endif // GAME_OPENING_SCREEN_LOGO_H
