#ifndef GAME_OPENING_SCREEN_LOGO_H
#define GAME_OPENING_SCREEN_LOGO_H

#include <stdint.h>

#define GAME_OPENING_SCREEN_LOGO_W 74
#define GAME_OPENING_SCREEN_LOGO_H 74

extern const uint16_t GAME_OPENING_SCREEN_LOGO[GAME_OPENING_SCREEN_LOGO_W * GAME_OPENING_SCREEN_LOGO_H];

#endif
