#ifndef GAME_SINGLE_LOGO_H
#define GAME_SINGLE_LOGO_H

#include <stdint.h>

#define GAME_SINGLE_LOGO_W 96
#define GAME_SINGLE_LOGO_H 64
#define GAME_SINGLE_LOGO_PAL_SIZE 16

extern const uint16_t GAME_SINGLE_LOGO_PAL[GAME_SINGLE_LOGO_PAL_SIZE];
extern const uint8_t  GAME_SINGLE_LOGO_IDX[(GAME_SINGLE_LOGO_W * GAME_SINGLE_LOGO_H) / 2];

#endif // GAME_SINGLE_LOGO_H
