#ifndef GAME_TOWER_LOGO_H
#define GAME_TOWER_LOGO_H

#include <stdint.h>

#define GAME_TOWER_LOGO_W 128
#define GAME_TOWER_LOGO_H 77
#define GAME_TOWER_LOGO_PAL_SIZE 16

extern const uint16_t GAME_TOWER_LOGO_PAL[GAME_TOWER_LOGO_PAL_SIZE];
extern const uint8_t  GAME_TOWER_LOGO_IDX[(GAME_TOWER_LOGO_W * GAME_TOWER_LOGO_H) / 2];

#endif // GAME_TOWER_LOGO_H
