#ifndef STORY_FINAL_SCENE_H
#define STORY_FINAL_SCENE_H

#include <stdint.h>

#define STORY_FINAL_SCENE_W 128
#define STORY_FINAL_SCENE_H 79
#define STORY_FINAL_SCENE_PAL_SIZE 16

extern const uint16_t STORY_FINAL_SCENE_PAL[STORY_FINAL_SCENE_PAL_SIZE];
extern const uint8_t  STORY_FINAL_SCENE_IDX[(STORY_FINAL_SCENE_W * STORY_FINAL_SCENE_H) / 2];

#endif // STORY_FINAL_SCENE_H
