#ifndef STORY_OPENING_SCENE_H
#define STORY_OPENING_SCENE_H

#include <stdint.h>

#define STORY_OPENING_SCENE_W 128
#define STORY_OPENING_SCENE_H 91
#define STORY_OPENING_SCENE_PAL_SIZE 16

extern const uint16_t STORY_OPENING_SCENE_PAL[STORY_OPENING_SCENE_PAL_SIZE];
extern const uint8_t  STORY_OPENING_SCENE_IDX[(STORY_OPENING_SCENE_W * STORY_OPENING_SCENE_H) / 2];

#endif // STORY_OPENING_SCENE_H
