#ifndef TOWER_WEREWOLF_H
#define TOWER_WEREWOLF_H

#include <stdint.h>

#define TOWER_WEREWOLF_W 96
#define TOWER_WEREWOLF_H 64
#define TOWER_WEREWOLF_PAL_SIZE 16

extern const uint16_t TOWER_WEREWOLF_PAL[TOWER_WEREWOLF_PAL_SIZE];
extern const uint8_t  TOWER_WEREWOLF_IDX[(TOWER_WEREWOLF_W * TOWER_WEREWOLF_H) / 2];

#endif // TOWER_WEREWOLF_H
