#ifndef TOWER_MINOTAUR_H
#define TOWER_MINOTAUR_H

#include <stdint.h>

#define TOWER_MINOTAUR_W 64
#define TOWER_MINOTAUR_H 37
#define TOWER_MINOTAUR_PAL_SIZE 16

extern const uint16_t TOWER_MINOTAUR_PAL[TOWER_MINOTAUR_PAL_SIZE];
extern const uint8_t  TOWER_MINOTAUR_IDX[(TOWER_MINOTAUR_W * TOWER_MINOTAUR_H) / 2];

#endif // TOWER_MINOTAUR_H
