#ifndef TOWER_BLACK_KNIGHT_H
#define TOWER_BLACK_KNIGHT_H

#include <stdint.h>

#define TOWER_BLACK_KNIGHT_W 64
#define TOWER_BLACK_KNIGHT_H 35
#define TOWER_BLACK_KNIGHT_PAL_SIZE 16

extern const uint16_t TOWER_BLACK_KNIGHT_PAL[TOWER_BLACK_KNIGHT_PAL_SIZE];
extern const uint8_t  TOWER_BLACK_KNIGHT_IDX[(TOWER_BLACK_KNIGHT_W * TOWER_BLACK_KNIGHT_H) / 2];

#endif // TOWER_BLACK_KNIGHT_H
